In [45]:
import pandas as pd
import os

In [46]:
import sys

path = os.path.expanduser('~/Documenti/Tesi-Magistrale')
os.chdir(path)
# Aggiunge la directory corrente al PATH per trovare 'src'
if os.getcwd() not in sys.path:
    sys.path.append(os.getcwd())

print(f"Directory attuale: {os.getcwd()}")

Directory attuale: /home/andy/Documenti/Tesi-Magistrale

In [47]:
omr = pd.read_csv("data/omr.csv")
omr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7753027 entries, 0 to 7753026
Data columns (total 5 columns):
 #   Column        Dtype
---  ------        -----
 0   subject_id    int64
 1   chartdate     object
 2   seq_num       int64
 3   result_name   object
 4   result_value  object
dtypes: int64(2), object(3)
memory usage: 295.8+ MB

In [48]:
omr.head()

   subject_id   chartdate  seq_num      result_name result_value
0    10000032  2180-04-27        1   Blood Pressure       110/65
1    10000032  2180-04-27        1     Weight (Lbs)           94
2    10000032  2180-05-07        1      BMI (kg/m2)         18.0
3    10000032  2180-05-07        1  Height (Inches)           60
4    10000032  2180-05-07        1     Weight (Lbs)        92.15

In [49]:
omr['result_name'].value_counts()

result_name
Blood Pressure                      2827801
Weight (Lbs)                        2145353
BMI (kg/m2)                         1901496
Height (Inches)                      814964
BMI                                   29021
Weight                                15108
Blood Pressure Sitting                 5757
Blood Pressure Standing (1 min)        4704
Blood Pressure Lying                   4359
Height                                 2365
Blood Pressure Standing (3 mins)       1255
Blood Pressure Standing                 565
eGFR                                    279
Name: count, dtype: int64

In [50]:
vitali = omr.pivot_table(index='subject_id', columns='result_name', values='result_value', aggfunc='first').reset_index()
vitali

result_name,subject_id,BMI,BMI (kg/m2),Blood Pressure,Blood Pressure Lying,Blood Pressure Sitting,Blood Pressure Standing,Blood Pressure Standing (1 min),Blood Pressure Standing (3 mins),Height,Height (Inches),Weight,Weight (Lbs),eGFR
0,10000032,NaN,18.0,110/65,NaN,NaN,NaN,NaN,NaN,NaN,60,NaN,94,NaN
1,10000084,NaN,24.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70,NaN,170,NaN
2,10000117,NaN,19.6,124/66,NaN,NaN,NaN,NaN,NaN,NaN,64.5,NaN,121,NaN
3,10000161,NaN,NaN,147/83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10000248,NaN,25.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68,NaN,168.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193496,19999636,NaN,NaN,118/58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,128,NaN
193497,19999733,NaN,NaN,108/70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,154,NaN
193498,19999750,NaN,27.7,153/93,NaN,NaN,NaN,NaN,NaN,NaN,68,NaN,182,NaN
193499,19999784,28.0,23.8,129/87,NaN,NaN,NaN,NaN,NaN,66.50,67,171.00,152,NaN
193500,19999828,NaN,25.7,130/88,NaN,NaN,NaN,NaN,NaN,NaN,64,NaN,150,NaN

In [51]:
vitali.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193501 entries, 0 to 193500
Data columns (total 14 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   subject_id                        193501 non-null  int64
 1   BMI                               16166 non-null   object
 2   BMI (kg/m2)                       153725 non-null  object
 3   Blood Pressure                    166869 non-null  object
 4   Blood Pressure Lying              2706 non-null    object
 5   Blood Pressure Sitting            3335 non-null    object
 6   Blood Pressure Standing           400 non-null     object
 7   Blood Pressure Standing (1 min)   2901 non-null    object
 8   Blood Pressure Standing (3 mins)  947 non-null     object
 9   Height                            1902 non-null    object
 10  Height (Inches)                   148359 non-null  object
 11  Weight                            11529 non-null   object
 12  Weight (Lbs)                      166872 non-null  object
 13  eGFR                              217 non-null     object
dtypes: int64(1), object(13)
memory usage: 20.7+ MB

In [57]:
vitali['Weight (Lbs)'] = pd.to_numeric(vitali['Weight (Lbs)'], errors='coerce')
vitali['Height (Inches)'] = pd.to_numeric(vitali['Height (Inches)'], errors='coerce')
vitali['Weight (kg)'] = vitali['Weight (Lbs)'] * 0.4536
vitali['Height (m)'] = vitali['Height (Inches)'] * 0.0254
vitali['Blood Pressure'] = pd.to_numeric(
    vitali['Blood Pressure'].astype(str).str.split('/').str[0],
    errors='coerce'
)
vitali

result_name,subject_id,BMI,BMI (kg/m2),Blood Pressure,Blood Pressure Lying,Blood Pressure Sitting,Blood Pressure Standing,Blood Pressure Standing (1 min),Blood Pressure Standing (3 mins),Height,Height (Inches),Weight,Weight (Lbs),eGFR,Weight (kg),Height (m)
0,10000032,NaN,18.0,110.0,NaN,NaN,NaN,NaN,NaN,NaN,60.0,NaN,94.0,NaN,42.6384,1.5240
1,10000084,NaN,24.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.0,NaN,170.0,NaN,77.1120,1.7780
2,10000117,NaN,19.6,124.0,NaN,NaN,NaN,NaN,NaN,NaN,64.5,NaN,121.0,NaN,54.8856,1.6383
3,10000161,NaN,NaN,147.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10000248,NaN,25.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.0,NaN,168.0,NaN,76.2048,1.7272
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193496,19999636,NaN,NaN,118.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,128.0,NaN,58.0608,NaN
193497,19999733,NaN,NaN,108.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,154.0,NaN,69.8544,NaN
193498,19999750,NaN,27.7,153.0,NaN,NaN,NaN,NaN,NaN,NaN,68.0,NaN,182.0,NaN,82.5552,1.7272
193499,19999784,28.0,23.8,129.0,NaN,NaN,NaN,NaN,NaN,66.50,67.0,171.00,152.0,NaN,68.9472,1.7018
193500,19999828,NaN,25.7,130.0,NaN,NaN,NaN,NaN,NaN,NaN,64.0,NaN,150.0,NaN,68.0400,1.6256

In [53]:
ospedale = pd.read_csv('data/icustays.csv')
ospedale

,subject_id,hadm_id,stay_id,first_careunit,last_careunit,intime,outtime,los
0,10000032,29079034,39553978,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2180-07-23 14:00:00,2180-07-23 23:50:47,0.410266
1,10000690,25860671,37081114,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2150-11-02 19:37:00,2150-11-06 17:03:17,3.893252
2,10000980,26913865,39765666,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2189-06-27 08:42:00,2189-06-27 20:38:27,0.497535
3,10001217,24597018,37067082,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),2157-11-20 19:18:02,2157-11-21 22:08:00,1.118032
4,10001217,27703517,34592300,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),2157-12-19 15:42:24,2157-12-20 14:27:41,0.948113
...,...,...,...,...,...,...,...,...
94453,19999442,26785317,32336619,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),2148-11-19 14:23:43,2148-11-26 13:12:15,6.950370
94454,19999625,25304202,31070865,Medical/Surgical Intensive Care Unit (MICU/SICU),Medical/Surgical Intensive Care Unit (MICU/SICU),2139-10-10 19:18:00,2139-10-11 18:21:28,0.960741
94455,19999828,25744818,36075953,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2149-01-08 18:12:00,2149-01-10 13:11:02,1.790995
94456,19999840,21033226,38978960,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),2164-09-12 09:26:28,2164-09-17 16:35:15,5.297766
94457,19999987,23865745,36195440,Trauma SICU (TSICU),Trauma SICU (TSICU),2145-11-02 22:59:00,2145-11-04 21:29:30,1.937847

In [54]:
pazienti = pd.read_csv('data/patients.csv')
pazienti

,subject_id,gender,anchor_age,anchor_year,anchor_year_group,dod
0,10000032,F,52,2180,2014 - 2016,2180-09-09
1,10000048,F,23,2126,2008 - 2010,NaN
2,10000058,F,33,2168,2020 - 2022,NaN
3,10000068,F,19,2160,2008 - 2010,NaN
4,10000084,M,72,2160,2017 - 2019,2161-02-13
...,...,...,...,...,...,...
364622,19999828,F,46,2147,2017 - 2019,NaN
364623,19999829,F,28,2186,2008 - 2010,NaN
364624,19999840,M,58,2164,2008 - 2010,2164-09-17
364625,19999914,F,49,2158,2017 - 2019,NaN
364626,19999987,F,57,2145,2011 - 2013,NaN

In [55]:
ammissioni = pd.read_csv('data/admissions.csv')
ammissioni

,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admit_provider_id,admission_location,discharge_location,insurance,language,marital_status,race,edregtime,edouttime,hospital_expire_flag
0,10000032,22595853,2180-05-06 22:23:00,2180-05-07 17:15:00,NaN,URGENT,P49AFC,TRANSFER FROM HOSPITAL,HOME,Medicaid,English,WIDOWED,WHITE,2180-05-06 19:17:00,2180-05-06 23:30:00,0
1,10000032,22841357,2180-06-26 18:27:00,2180-06-27 18:49:00,NaN,EW EMER.,P784FA,EMERGENCY ROOM,HOME,Medicaid,English,WIDOWED,WHITE,2180-06-26 15:54:00,2180-06-26 21:31:00,0
2,10000032,25742920,2180-08-05 23:44:00,2180-08-07 17:50:00,NaN,EW EMER.,P19UTS,EMERGENCY ROOM,HOSPICE,Medicaid,English,WIDOWED,WHITE,2180-08-05 20:58:00,2180-08-06 01:44:00,0
3,10000032,29079034,2180-07-23 12:35:00,2180-07-25 17:55:00,NaN,EW EMER.,P06OTX,EMERGENCY ROOM,HOME,Medicaid,English,WIDOWED,WHITE,2180-07-23 05:54:00,2180-07-23 14:00:00,0
4,10000068,25022803,2160-03-03 23:16:00,2160-03-04 06:26:00,NaN,EU OBSERVATION,P39NWO,EMERGENCY ROOM,NaN,NaN,English,SINGLE,WHITE,2160-03-03 21:55:00,2160-03-04 06:26:00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
546023,19999828,25744818,2149-01-08 16:44:00,2149-01-18 17:00:00,NaN,EW EMER.,P13JMH,TRANSFER FROM HOSPITAL,HOME HEALTH CARE,Medicaid,English,SINGLE,WHITE,2149-01-08 09:11:00,2149-01-08 18:12:00,0
546024,19999828,29734428,2147-07-18 16:23:00,2147-08-04 18:10:00,NaN,EW EMER.,P38XL8,PHYSICIAN REFERRAL,HOME HEALTH CARE,Medicaid,English,SINGLE,WHITE,2147-07-17 17:18:00,2147-07-18 17:34:00,0
546025,19999840,21033226,2164-09-10 13:47:00,2164-09-17 13:42:00,2164-09-17 13:42:00,EW EMER.,P33612,EMERGENCY ROOM,DIED,Private,English,WIDOWED,WHITE,2164-09-10 11:09:00,2164-09-10 14:46:00,1
546026,19999840,26071774,2164-07-25 00:27:00,2164-07-28 12:15:00,NaN,EW EMER.,P036NA,EMERGENCY ROOM,HOME,Private,English,WIDOWED,WHITE,2164-07-24 21:16:00,2164-07-25 01:20:00,0
546027,19999987,23865745,2145-11-02 21:38:00,2145-11-11 12:57:00,NaN,EW EMER.,P95A45,EMERGENCY ROOM,REHAB,Medicaid,English,NaN,UNKNOWN,2145-11-02 19:28:00,2145-11-02 22:59:00,0