In [9]:
import sys
import os

path = os.path.expanduser('~/Documenti/Tesi-Magistrale')
os.chdir(path)
# Aggiunge la directory corrente al PATH per trovare 'src'
if os.getcwd() not in sys.path:
    sys.path.append(os.getcwd())

print(f"Directory attuale: {os.getcwd()}")

Directory attuale: /home/andy/Documenti/Tesi-Magistrale

In [11]:
metadati = pd.read_csv("data/mimic-cxr-2.0.0-metadata.csv")
metadati = metadati[metadati['ViewPosition'] != 'LATERAL']
metadati

,dicom_id,subject_id,study_id,PerformedProcedureStepDescription,ViewPosition,Rows,Columns,StudyDate,StudyTime,ProcedureCodeSequence_CodeMeaning,ViewCodeSequence_CodeMeaning,PatientOrientationCodeSequence_CodeMeaning
0,02aa804e-bde0afdd-112c0b34-7bc16630-4e384014,10000032,50414267,CHEST (PA AND LAT),PA,3056,2544,21800506,213014.531,CHEST (PA AND LAT),postero-anterior,Erect
2,2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab,10000032,53189527,CHEST (PA AND LAT),PA,3056,2544,21800626,165500.312,CHEST (PA AND LAT),postero-anterior,Erect
4,68b5c4b1-227d0485-9cc38c3f-7b84ab51-4b472714,10000032,53911762,CHEST (PORTABLE AP),AP,2705,2539,21800723,80556.875,CHEST (PORTABLE AP),antero-posterior,NaN
5,fffabebf-74fd3a1f-673b6b41-96ec0ac9-2ab69818,10000032,53911762,CHEST (PORTABLE AP),AP,2906,2258,21800723,80556.875,CHEST (PORTABLE AP),antero-posterior,Erect
6,ea030e7a-2e3b1346-bc518786-7a8fd698-f673b44c,10000032,56699142,CHEST (PORTABLE AP),AP,3056,2544,21800805,234424.765,CHEST (PORTABLE AP),antero-posterior,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
377104,3fcd0406-9b111603-feae7033-96632b3a-111333e5,19999733,57132437,CHEST (PA AND LAT),PA,3056,2544,21520708,224550.171,CHEST (PA AND LAT),postero-anterior,Erect
377105,428e2c18-5721d8f3-35a05001-36f3d080-9053b83c,19999733,57132437,CHEST (PA AND LAT),PA,3056,2544,21520708,224550.171,CHEST (PA AND LAT),postero-anterior,Erect
377107,58766883-376a15ce-3b323a28-6af950a0-16b793bd,19999987,55368167,CHEST (PORTABLE AP),AP,2544,3056,21451104,51448.218,CHEST (PORTABLE AP),antero-posterior,Erect
377108,7ba273af-3d290f8d-e28d0ab4-484b7a86-7fc12b08,19999987,58621812,CHEST (PORTABLE AP),AP,3056,2544,21451102,202809.234,CHEST (PORTABLE AP),antero-posterior,Erect
377109,1a1fe7e3-cbac5d93-b339aeda-86bb86b5-4f31e82e,19999987,58971208,CHEST (PORTABLE AP),AP,3056,2544,21451103,50507.625,CHEST (PORTABLE AP),antero-posterior,Recumbent

In [12]:
lista_immagini = []
ricerca = Path(os.path.join("data", "MIMIC_SUPER_RES_24K"))
for file_path in ricerca.rglob('*.jpg'):
    dicom_id = file_path.stem
    lista_immagini.append({'dicom_id': dicom_id, 'path_immagine': str(file_path)})
immagini = pd.DataFrame(lista_immagini)
immagini['path_immagine'] = immagini['path_immagine'].str.replace(str(path+"/"), "data/", regex=False) # pulisci il path
immagini['dicom_id'] = immagini['dicom_id'].astype(str)
print(f"{len(immagini)} immagini")
immagini.head()

24000 immagini

,dicom_id,path_immagine
0,62456122-1887ff8c-ef1cba37-270fe1ac-c88ef7fc,data/MIMIC_SUPER_RES_24K/62456122-1887ff8c-ef1...
1,152c3005-d0c7bf7a-4c0f7935-e82aef6e-bed96e2e,data/MIMIC_SUPER_RES_24K/152c3005-d0c7bf7a-4c0...
2,c4a20cd5-94e7d182-0bbca8a9-797c8bf5-7e12e050,data/MIMIC_SUPER_RES_24K/c4a20cd5-94e7d182-0bb...
3,064741c9-95255009-ae0c53ee-ccb54164-21b77bbb,data/MIMIC_SUPER_RES_24K/064741c9-95255009-ae0...
4,2150ba84-0f87ae6f-a7132d8e-8b02fb6c-99745702,data/MIMIC_SUPER_RES_24K/2150ba84-0f87ae6f-a71...

In [13]:
dataset = immagini.merge(metadati, how='left', on='dicom_id')
dataset

,dicom_id,path_immagine,subject_id,study_id,PerformedProcedureStepDescription,ViewPosition,Rows,Columns,StudyDate,StudyTime,ProcedureCodeSequence_CodeMeaning,ViewCodeSequence_CodeMeaning,PatientOrientationCodeSequence_CodeMeaning
0,62456122-1887ff8c-ef1cba37-270fe1ac-c88ef7fc,data/MIMIC_SUPER_RES_24K/62456122-1887ff8c-ef1...,16994397,52464683,CHEST (PORTABLE AP),AP,2539,3050,21130701,170824.250,CHEST (PORTABLE AP),antero-posterior,Erect
1,152c3005-d0c7bf7a-4c0f7935-e82aef6e-bed96e2e,data/MIMIC_SUPER_RES_24K/152c3005-d0c7bf7a-4c0...,14716808,57354809,NaN,PA,2022,1736,21990614,134835.000,CHEST (PA AND LAT),postero-anterior,Erect
2,c4a20cd5-94e7d182-0bbca8a9-797c8bf5-7e12e050,data/MIMIC_SUPER_RES_24K/c4a20cd5-94e7d182-0bb...,14073672,51550911,CHEST (PA AND LAT),PA,2952,2500,21701024,155525.203,CHEST (PA AND LAT),postero-anterior,Erect
3,064741c9-95255009-ae0c53ee-ccb54164-21b77bbb,data/MIMIC_SUPER_RES_24K/064741c9-95255009-ae0...,16012667,50941182,CHEST (PORTABLE AP),AP,3035,2539,21320611,33907.343,CHEST (PORTABLE AP),antero-posterior,Erect
4,2150ba84-0f87ae6f-a7132d8e-8b02fb6c-99745702,data/MIMIC_SUPER_RES_24K/2150ba84-0f87ae6f-a71...,17686783,50124464,CHEST (PORTABLE AP),AP,3056,2544,21720209,51446.375,CHEST (PORTABLE AP),antero-posterior,Erect
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23995,ea8df8e0-364885ff-4faf78fd-cab5c93b-a88c32b4,data/MIMIC_SUPER_RES_24K/ea8df8e0-364885ff-4fa...,16117323,56937638,CHEST (PA AND LAT),AP,2544,3056,21911114,223409.140,CHEST (PA AND LAT),antero-posterior,Erect
23996,eb76f199-dc94ddad-e7095f97-8671879f-4606de18,data/MIMIC_SUPER_RES_24K/eb76f199-dc94ddad-e70...,14522445,57330720,CHEST (PA AND LAT),PA,2544,3056,21651024,185516.984,CHEST (PA AND LAT),postero-anterior,Erect
23997,f2c56131-41b8d79c-8c49cff3-3c3fa85d-9bf49e1a,data/MIMIC_SUPER_RES_24K/f2c56131-41b8d79c-8c4...,11545313,59904294,CHEST (PA AND LAT),AP,3056,2544,21680706,143016.859,CHEST (PA AND LAT),antero-posterior,Erect
23998,4a33432b-d891a4e8-44a53063-4e1b08bf-dd30ca6a,data/MIMIC_SUPER_RES_24K/4a33432b-d891a4e8-44a...,12885435,52596566,CHEST (PORTABLE AP),AP,3056,2544,21270108,215121.656,CHEST (PORTABLE AP),antero-posterior,NaN
23999,cc2cf9cb-14a3d1da-99825276-f442100a-716ce836,data/MIMIC_SUPER_RES_24K/cc2cf9cb-14a3d1da-998...,13050559,51750973,CHEST (PORTABLE AP),AP,2539,2935,21470730,171605.968,CHEST (PORTABLE AP),antero-posterior,NaN

In [17]:
mappa_referti = {}
for _, row in dataset.iterrows():
    s_id = str(row['study_id'])
    p_id = str(row['subject_id'])
    nome_originale = f"s{s_id}.txt"
    nome_nuovo = f"p{p_id}_s{s_id}.txt"
    mappa_referti[nome_originale] = nome_nuovo

print(f"Dobbiamo estrarre esattamente {len(mappa_referti)} referti testuali unici.")

# --- 3. SCANSIONE ED ESTRAZIONE (SENZA GUARDARE LE CARTELLE) ---
cartella_mimic = os.path.join("data", "mimic-cxr-reports")
cartella_destinazione = os.path.join("data", "referti_esatti_24k")
os.makedirs(cartella_destinazione, exist_ok=True)

referti_trovati = []

print("Scansione della cartella madre dei referti in corso...")
for radice, _, file in os.walk(cartella_mimic):
    for nome_file in file:
        # Se il file è esattamente uno di quelli che stiamo cercando:
        if nome_file in mappa_referti:
            percorso_sorgente = os.path.join(radice, nome_file)
            nuovo_nome = mappa_referti[nome_file]
            percorso_destinazione = os.path.join(cartella_destinazione, nuovo_nome)
            
            referti_trovati.append((percorso_sorgente, percorso_destinazione))

print(f"Trovati fisicamente {len(referti_trovati)} referti su {len(mappa_referti)}.")

# --- 4. COPIA DEI FILE ---
if len(referti_trovati) > 0:
    with tqdm(total=len(referti_trovati), desc="Copia Referti") as pbar:
        for sorgente, destinazione in referti_trovati:
            shutil.copy2(sorgente, destinazione)
            pbar.update(1)
            
    print(f"\n✅ Estrazione chirurgica completata! I file perfetti sono in: {cartella_destinazione}")
else:
    print("Errore: Nessun referto trovato. Controlla che il percorso 'data/mimic-cxr-reports' sia corretto!")

Dobbiamo estrarre esattamente 23730 referti testuali unici.
Scansione della cartella madre dei referti in corso...
Trovati fisicamente 23730 referti su 23730.

Copia Referti: 100%|██████████| 23730/23730 [00:04<00:00, 5030.87it/s]

✅ Estrazione chirurgica completata! I file perfetti sono in: data/referti_esatti_24k